### ISSUE TITLE
Function for setPinpullups is bugged

### ISSUE THREAD

**Issue by YindSoft** [rikvermeer/mcp23017#2]
Hi,

The function to set the pullups wasn't right, I fixed it for you.

/**
 * Set the internal 100K pull-up resistors for an individual pin
 *
 * @param pin Pin 0 to 15
 * @param value Value where 1 = enabled and 0 = disabled
 */
MCP23017.prototype.setPinPullup = function (pin, value) {
	if (pin < 8) {
		this.config.port_a_pullup = this.updateByte(this.config.port_a_pullup, pin, value);
		this.bus.writeByteSync(this.config.ioaddress, registers.GPPUA, this.config.port_a_pullup);
	} else {
		this.config.port_b_pullup = this.updateByte(this.config.port_b_pullup, pin - 8, value);
		this.bus.writeByteSync(this.config.ioaddress, registers.GPPUB, this.config.port_b_pullup);
	}
};

**Comment by rikvermeer** [comment]
(Better late than never,) I thank you for this contribution :)
