### ISSUE TITLE
setInterruptOnPin and invertPin need Pin-8 semantics?

### ISSUE THREAD

**Issue by lynniemagoo** [rikvermeer/mcp23017#3]
I recently started using this NPM module and made some additions to the module to support keeping track of the output latch for both Port A and Port B.  

Prior to adding my changes and making a pull request, I reviewed recent changes and will note some differences around the 'pin' derivate functions.

For Port B...   I noticed that in some places, the line bolded below
**_pin = pin - 8;_**
this.config.port_b_value = this.updateByte(this.config.port_b_value, **_pin_**, value);

is in place just before call to updateByte.  Above lines from 'writePin' as an example.

In other locations, for port B, there is a call to updateByte for example:
**_this.config.portb_pullup = updateByte(this.config.port_b_pullup, pin - 8, value);_**

from 'writePinPullups' as an example.

Functionally, these behave identically but for consistency, wouldn't we want them all the same?  That includes calls the checkBit(byte,bit).

I am currently using setPortInterrrupts() and invertPort() and have no issues.  However, I noticed that these 2 functions below don't have the pin - 8 semantics for Port B.  I think they need them.

```
/**
 * Enable interrupts for the selected pin
 *
 * @param pin Pins 0 to 15
 * @param value Value where 0 = interrupt disabled, 1 = interrupt enabled
 */
MCP23017.prototype.setInterruptOnPin = function (pin, value) {
	if (pin < 8) {
		this.config.inta = this.updateByte(this.config.inta, pin, value);
		this.bus.writeByteSync(this.config.ioaddress, registers.GPINTENA, this.config.inta);
	} else {
                // modify to add pin - 8
		this.config.intb = this.updateByte(this.config.intb, pin - 8, value);
		this.bus.writeByteSync(this.config.ioaddress, registers.GPINTENB, this.config.intb);
	}
};

/**
 * Invert the polarity of the selected pin
 *
 * @param pin Pins 0 to 15
 * @param polarity Polarity of the input pin, 0 = same logic state, 1 = inverted logic state
 */
MCP23017.prototype.invertPin = function (pin, polarity) {
	if (pin < 8) {
		this.config.port_a_polarity = this.updateByte(this.config.port_a_polarity, pin, polarity);
		this.bus.writeByteSync(this.config.ioaddress, registers.IPOLA, this.config.port_a_polarity);
	} else {
                // modify to add pin - 8
		_this.config.port_b_polarity = this.updateByte(this.config.port_b_polarity, pin -8, polarity);
		this.bus.writeByteSync(this.config.ioaddress, registers.IPOLB, this.config.port_b_polarity);
	}
};


```

**Comment by rikvermeer** [comment]
I have merged your changes. Could you test this please? Since I have no MCP2017 lying around at this moment.

Thanks for your contribution!
