### ISSUE TITLE
Provide ability to read Pin/Port output latch and Pullup values.

### ISSUE THREAD

**Issue by lynniemagoo** [rikvermeer/mcp23017#5]
Want to add this capability as well as cleanup remaining pin - 8 syntax.

**Comment by rikvermeer** [comment]
Can you clarify a bit? I've recently read the MCP23017 datasheet and I don't remember reading anything about latching outputs. Could you point me to the docs on that one?

The state of the pin/port can be read by readPin/readPort so i guess you're not referring to those methods, right?

The pullup values can be read from the local config. The config is updated at start of the script and updated on each change. I could agree with you that it should be read from the chip, but in the end the states shouldn't differ.

Again, thanks for you interest and collaboration

**Comment by lynniemagoo** [comment]
The idea behind the latch addition is that if a port is an output port and you want to know what value you last wrote to it, you can read the latch value.  I specifically did not test the chip to know if the readPort and readPortOutputLatches reported the exact same value or a case where pins on a port were both Input and Output.  

Therefore, it is up to the user to know if pins on said port are marked as output or input and apply the appropriate bitmask.  

Here's where I sourced my change from....

Section 3.4 Page 16 of the MCP23017 datasheet 

https://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf

states...

**3.4 GPIO Port**
The GPIO module is a general purpose, 16-bit wide,
bidirectional port that is functionally split into two
8-bit wide ports.
The GPIO module contains the data ports (GPIOn),
internal pull-up resistors and the output latches
(OLATn).
**Reading the GPIOn register reads the value on the
port. Reading the OLATn register only reads the
latches, not the actual value on the port.**
Writing to the GPIOn register actually causes a write to
the latches (OLATn). Writing to the OLATn register
forces the associated output drivers to drive to the level
in OLATn. Pins configured as inputs turn off the
associated output driver and put it in high-impedance.


I have a change ready to go for this one.  I'll go ahead and open the pull request for you to review.

**Comment by lynniemagoo** [comment]
Confirmed merge.  Thanks!.
