### ISSUE TITLE
This module by default configures interrupt to Active Low and not Open Drain

### ISSUE THREAD

**Issue by lynniemagoo** [rikvermeer/mcp23017#7]
Rick,
I wanted to attempt multiplexing many MCP23017's on same I2C bus and having them all share a single interrupt pin on the controller.  The current module default value is not ideal and can cause power supply shorting as the default Interrupt behavior is not Open-Drain.  If only changing default ioconfig value, we'd likely want to enable ODR such that interrupt will be Active-low and Hi-Z when not active.
The **POR/RST** default values of the chip are:
**IOCON** = 0x00 
**IODIR**  = 0xFF (all pins are inputs)
**INTFA** = 0x00 (no interrupts will be fired)
**INTFB** = 0X00 (no interrupts will be fired)

I see that when this existing module starts up, it is setting IOCON to 0x20.
In reviewing the datasheet, for Registers 3-6, the setup is as follows:
**BANK=0x80** (Current module IOCON default CLEARS forcing Bank 0 register mapping – by default Bank0 supports sequential addressing whereas Bank1 does not)
**MIRROR=0x40** (Current module IOCON default CLEARS this which allows turns off mirroring)
**SEQOP=0x20** (Current module IOCON default SETS this which turns off sequential addressing – No reason to do this as we only read 1 byte per operation)
**DISSLW=0x10** (Current module IOCON default CLEARS this which enables slew rate by default)
**HAEN=0x08** (Current module CLEARS this bit which only applies to MCP23S17)
**ODR=0x04** (Current module CLEARS this bit meaning that interrupt pins will be either high or low depending on value of INTPOL below.  Not ideal for modules sharing a common interrupt GPIO on the controller).
**INTPOL=0x02** (Current module CLEARS this bit meaning that interrupts will be active LOW and therefore be HIGH when not active as ODR is not set.).
**UNUSED=0x01**
**SEQOP=1** states address pointer does not increment automatically (prevents reading multiple bytes via readWord/readBlock in I2C which would minimize I2C requests as we could read/write 2 bytes at a time assuming Bank0 register addressing is in place). 

Ideally, I think we’d want to change the ioconfig default to either 0x24 (Disable Sequential addressing and enabling Open-Drain) or 0x04 (Enables Sequential addressing as the default does and enabling Open-Drain).

Worst case, as we already have method to set InterruptPolarity and mirrorInterrupts, here’s what I propose:

Change the default of ioconfig from 0x20 to 0x04 (activate Open-Drain by default and enable Sequential addressing as module currently only transacts 1 byte at time) and then we could:

Add a new method to support configuration of interrupt open-drain (0 = Active Driver Output, 1 = Open Drain)
MCP23017.prototype.setInterruptOpenDrain = function (port, value)

Let me know your thoughts here and if you’d be amicable to making this change.  I have no issues doing a fork and supporting my own efforts but would like to keep all the code here.

**Comment by rikvermeer** [comment]
dear lynnie magoo,

It's been a while since I've looked at this code and it was also learning
in progress. At that time I was mostly concerned with driving output and
not so much with the interrupts. I just put it here on github for others to
use or to continue on. For that sake I'd love your contribution.

I see no reason why not to change the default to 0x04. As you pointed out
it makes more sense to enable sequential addressing.

Shall I give you access to the repo?

Kind regards,
Rik

**Comment by lynniemagoo** [comment]
You already did and I fixed a long time bug last night.  I’ve got some other restructuring changes that I’m working on so I will make those as well in the next couple of weeks.

**Comment by lynniemagoo** [comment]
Rik,

I'm almost done with my changes.  However, there's a matter of function names that has been bugging me for a very long time.

For example, we have get/set function pairs.  As part of my enhancements, I'm adding getLastXXXX functions.

In reality, I was thinking that we could have something like:
readPortValue(port)
writePortValue(port)
getPortValue(port) - which returns the in-memory configuration value saved from either last read/write of the register.

Then for any function related writing the IOCON register, I was thinking about:
configureInterruptMirror(value);
configureInterruptOpenDrain(value);
configureInterruptPolarity(value);
configureDisableSDASlewRate(value);

Let me know your thoughts on this please.  I'm also in the US and if needed could do a zoom or facetime call to discuss.
I'm also game to save off the current release as a 1.0.0 version via tagging and then put a 2.0.0 version out on master.

Thanks,
Lyndel

In the meantime, here's a preview of the changes I've made so far.

This is a work in progress.  I'm continuing to make minor internal changes.  Here's what I have so far.
[mcp23017.zip](https://github.com/rikvermeer/mcp23017/files/10540815/mcp23017.zip)

**Comment by lynniemagoo** [comment]
All updates for Version 1.0.0 have been completed.
